on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compile notes
        uses: xu-cheng/latex-action@v2
        with:
          root_file: notes.tex
      - name: Compile presentation
        uses: xu-cheng/latex-action@v2
        with:
          root_file: presentation.tex
      - name: Compile handout
        uses: xu-cheng/latex-action@v2
        with:
          root_file: handout.tex
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload notes
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/notes.pdf
          asset_name: notes.pdf
          asset_content_type: application/pdf
      - name: Upload presentation
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/presentation.pdf
          asset_name: presentation.pdf
          asset_content_type: application/pdf
      - name: Upload handout
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/handout.pdf
          asset_name: handout.pdf
          asset_content_type: application/pdf
